---
title: "Descriptives"
format: html
editor: visual
---

# Final Malawi Descriptives



```{r}


# exposure to sister maternal mortality
prev_sd_del_b4Dur_everSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "prev_sd_del_b4Dur_ever", useNA=F, roundby=2)
})

prev_sd_del_b4Dur_ever.sum <- summarySection(prev_sd_del_b4Dur_everSum.list, "prev_sd_del_b4Dur_ever::")
rm(prev_sd_del_b4Dur_everSum.list)


# exposure to previous under 5 death
prec_u5DeathSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "prec_u5Death", useNA=F, roundby=2)
})

prec_u5Death.sum <- summarySection(prec_u5DeathSum.list, "prec_u5Death::")
rm(prec_u5DeathSum.list)


# exposure to previous infant death
prec_infDeathSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "prec_infDeath", useNA=F, roundby=2)
})

prec_infDeath.sum <- summarySection(prec_infDeathSum.list, "prec_infDeath::")
rm(prec_infDeathSum.list)


# exposure to previous neonatal death
prec_neoDeathSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "prec_neoDeath", useNA=F, roundby=2)
})

prec_neoDeath.sum <- summarySection(prec_neoDeathSum.list, "prec_neoDeath::")
rm(prec_neoDeathSum.list)


# rural
ruralSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "rural", useNA=F, roundby=2)
})

rural.sum <- summarySection(ruralSum.list, "rural::")
rm(ruralSum.list)

# everUnion
everUnionSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "everUnion", useNA=F, roundby=2)
})

everUnion.sum <- summarySection(everUnionSum.list, "everUnion::")
rm(everUnionSum.list)


# wealth Index
wealthIndexSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "wealthIndex", useNA=F, roundby=2)
})


wealthIndex.sum <- summarySection(wealthIndexSum.list, "wealthIndex::")
rm(wealthIndexSum.list)


# education Level
edLevelSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "edLevel", useNA=F, roundby=2)
})

edLevel.sum <- summarySection(edLevelSum.list, "edLevel::")
rm(edLevelSum.list)

# age group
atCBirth_5grpSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "atCBirth_5grp", useNA=F, roundby=2)
})

atCBirth_5grp.sum <- summarySection(atCBirth_5grpSum.list, "atCBirth_5grp::")
rm(atCBirth_5grpSum.list)


# exposure to sister maternal mortality
rh_anc_4vsSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "rh_anc_4vs", useNA=F, roundby=2)
})

rh_anc_4vs.sum <- summarySection(rh_anc_4vsSum.list, "rh_anc_4vs::")
rm(rh_anc_4vsSum.list)


# exposure to sister maternal mortality
rh_del_fbdSum.list <- lapply(modelData.list, function(x) {
  # df <- subset(x, everUnion ==0)
  cat_sum(x, "rh_del_fbd", useNA=F, roundby=2)
})

rh_del_fbd.sum <- summarySection(rh_del_fbdSum.list, "rh_del_fbd::")
rm(rh_del_fbdSum.list)


```


## Put this into a table

```{r}

# bind these into a single table
table1_cat <- rbind(rh_anc_4vs.sum,
                    rh_del_fbd.sum,
                    prev_sd_del_b4Dur_ever.sum, 
                    prec_u5Death.sum, 
                    prec_infDeath.sum, 
                    prec_neoDeath.sum,
                    atCBirth_5grp.sum,
                    rural.sum, 
                    everUnion.sum, 
                    wealthIndex.sum,
                    edLevel.sum
                    )

# tidy up the table
#   transform the matrix
table1_cat.df <- t(table1_cat) |> as.data.frame()
# #   drop the "V1." from the row name
# rownames(table1_cat.df) <- stringr::str_trunc(rownames(table1_cat.df), 3, side="left", ellipsis = "")

# get total respondents
table1_cat.df$`Total Respondents` <- NA
# table1_cat.df<-table1_cat.df[!rownames(table1_cat.df) %in% c("lvl"),]

for (i in rownames(table1_cat.df)) {
  table1_cat.df[i, "Total Respondents"] <- nrow(modelData.list[[i]])

}


library(openxlsx)

table1 <- openxlsx::createWorkbook()
table1.sheet <- openxlsx::addWorksheet(table1, "Table1")

openxlsx::writeData(table1, table1.sheet, table1_cat.df, rowNames = T)

saveWorkbook(table1, file=file.path(getwd(), "data", "table1.xlsx"), overwrite = T)



```


